version: '3'

services:
    db:
        image: "postgres:12"
        restart: always
        environment:
            - POSTGRES_USER=proxy_py
            - POSTGRES_PASSWORD=proxy_py
            - POSTGRES_DB=proxy_py
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            proxy_py_net:
                ipv4_address: 172.16.1.2
    core:
        image: "kom46/proxy_py:exec_bug"
        working_dir: /proxy_py
        command: >
            bash -c "poetry env use .venv/bin/python3 &&
                    poetry install --without=dev &&
                    poetry run ./run.sh
                    "
        restart: always
        ports:
            - "55555:55555"
        environment:
            - PROXY_PY_PROXY_PROVIDER_SERVER_ADDRESS={'HOST':'0.0.0.0','PORT':55555}
            - PROXY_PY_DATABASE_CONNECTION_KWARGS={'host':'db','database':'proxy_py','user':'proxy_py','password':'proxy_py'}
        depends_on:
            - db
        networks:
            proxy_py_net:
                ipv4_address: 172.16.1.3


volumes: 
    db_data:

networks:
    proxy_py_net:
        ipam:
            config:
                - subnet: 172.16.1.0/24
